name-template: "v$RESOLVED_VERSION "
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "documentation"
      - "ci"
      - "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
autolabeler:
  - label: "feature"
    title:
      - "/^feat/"
  - label: "bug"
    title:
      - "/^fix/"
  - label: "chore"
    title:
      - "/^chore/"
  - label: "documentation"
    title:
      - "/^docs/"
  - label: "ci"
    title:
      - "/^ci/"
template: |
  ## What's Changed
  $CHANGES
