language: "pt-BR"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  tools:
    ast-grep:
      enabled: true
    minswap:
      enabled: false
chat:
  auto_reply: true
